#pragma once

/*
██╗ ██████╗     ███╗   ███╗ █████╗ ██████╗ 
██║██╔═══██╗    ████╗ ████║██╔══██╗██╔══██╗
██║██║   ██║    ██╔████╔██║███████║██████╔╝
██║██║   ██║    ██║╚██╔╝██║██╔══██║██╔═══╝ 
██║╚██████╔╝    ██║ ╚═╝ ██║██║  ██║██║     
╚═╝ ╚═════╝     ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     v2022
*/

//PWM
#define PWM_HANG_LEFT_SERVO_STOP 0
#define PWM_HANG_RIGHT_SERVO_STOP 1
#define PWM_HANG_RACHET_AND_PAWL 2
#define PWM_SHOOTER_HOOD_SERVO 3
#define PWM_BLINKY_BLINKY 4

//CAN
#define CAN_HANG_WINCH_MOTOR 2
#define CAN_HANG_ENCODER_A 21
#define CAN_HANG_ENCODER_B 22

#define CAN_INTAKE_MOTOR 3

#define CAN_STORAGE_STAGE_ONE 4
#define CAN_STORAGE_STAGE_TWO 5

#define CAN_SHOOTER_TRANSITION_MOTOR 6
#define CAN_SHOOTER_LEFT_FLYWHEEL_MOTOR 7
#define CAN_SHOOTER_RIGHT_FLYWHEEL_MOTOR 8

#define CAN_SWERVE_FL_DRIVE_MOTOR 9
#define CAN_SWERVE_BL_DRIVE_MOTOR 10
#define CAN_SWERVE_BR_DRIVE_MOTOR 11
#define CAN_SWERVE_FR_DRIVE_MOTOR 12

#define CAN_SWERVE_FL_ROT_MOTOR 13
#define CAN_SWERVE_BL_ROT_MOTOR 14
#define CAN_SWERVE_BR_ROT_MOTOR 15
#define CAN_SWERVE_FR_ROT_MOTOR 16

#define CAN_SWERVE_FL_ROT_CAN_CODER 17
#define CAN_SWERVE_BL_ROT_CAN_CODER 18
#define CAN_SWERVE_BR_ROT_CAN_CODER 19
#define CAN_SWERVE_FR_ROT_CAN_CODER 20

//DIO
#define DIO_HANG_OPTICAL_HOME_SENSOR 0
#define DIO_HANG_FLAG_SENSOR_LEFT 1
#define DIO_HANG_FLAG_SENSOR_RIGHT 2

#define DIO_INTAKE_BANNER_ENTRANCE 3
#define DIO_STORAGE_BANNER_STAGE_ONE 4
#define DIO_STORAGE_BANNER_STAGE_TWO 5
#define DIO_SHOOTER_BANNER_LEFT_ROBOT 6
#define DIO_HANG_RATCHET_BEAM_BREAK 7

//ANALOG
#define ANALOG_SHOOTER_HOOD_POTENTIOMETER 0

//PCM1
#define PCM1_HANG_PIVOT_1_RETRACT 0
#define PCM1_HANG_PIVOT_1_EXTEND 1

#define PCM1_HANG_BRAKE_PISTON_RETRACT 2
#define PCM1_HANG_BRAKE_PISTON_EXTEND 3

#define PCM1_HANG_2_RETRACT 4
#define PCM1_HANG_2_EXTEND 5


//PCM2

#define INTAKE_LEFT_PIVOT_EXTEND 4
#define INTAKE_LEFT_PIVOT_RETRACT 5

#define INTAKE_RIGHT_PIVOT_EXTEND 6
#define INTAKE_RIGHT_PIVOT_RETRACT 7

//RELAY